spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}

jwt:
  secrets:
    access-token: ${ACCESS_TOKEN_SECRET}
    refresh-token: ${REFRESH_TOKEN_SECRET}

encryption:
  key: ${ENCRYPTION_KEY}
  algo: ${ENCRYPTION_ALGO}

client:
  url: ${CLIENT_URL}