server:
  port: 9090
  ssl:
    key-store: classpath:${SSL_KEY_STORE:keystore.p12}
    key-store-password: ${SSL_KEY_STORE_PASSWORD}
    key-store-type: ${SSL_KEY_STORE_TYPE:PKCS12}
    key-alias: ${SSL_KEY_ALIAS:messenger}


spring:
  application:
    name: Server
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  sql:
    init:
      platform: postgres

  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update

jwt:
  durations:
    access-token: 900000          # 15 minutes in milliseconds
    refresh-token: 2592000000      # 30 days in milliseconds