server:
  port: 9090

spring:
  application:
    name: Server
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  sql:
    init:
      platform: postgres

  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update

jwt:
  durations:
    access-token: 900000          # 15 minutes in milliseconds
    refresh-token: 2592000000      # 30 days in milliseconds