services:
  server:
    build: .
    image: server:latest
    container_name: server
    env_file:
      - .env
    ports:
      - "9090:9090"
      - "9000:9000"
    depends_on:
      - db
    networks:
      - server_network
    command: sh /app/entrypoint.sh
    environment:
      SPRING_PROFILES_ACTIVE: dev

  db:
    image: postgres:17
    container_name: db
    environment:
      POSTGRES_USER: ${DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
      POSTGRES_DB: ${DATASOURCE_DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - server_network

networks:
  server_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local